### ISSUE TITLE
Issues with CNN code example

### ISSUE THREAD

**Issue by yanivnik** [AhmedImtiazPrio/splinecam#6]
Thank you for publishing the code. The method is interesting and seems like it could be helpful to me on a current research project.

For that reason I tried running the code examples, but I'm having some trouble getting them work, mainly around the shape of the projection matrix.

I tried running the "visualize_cnn_random.py" example (without any edit to the code), and I get the following error - 
```
Traceback (most recent call last):
 ....
  File "splinecam/splinecam/wrappers.py", line 415, in verify
    fwd_val = self.layers.forward(A)
  File "splinecam/splinecam/wrappers.py", line 59, in forward
    return (self.Abw[...,:-1] @ x.T + self.Abw[...,-1:]).T
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3072x1 and 2x1)
```

The input to the function `x` is with shape `(1,2)`, the shape of the projection matrix `T` (and `self.Abw`) is `(3072,2)` .
It is unclear to me why the index is only accessed until the last element (`self.Abw[...**,:-1**]`) there. Could this be the cause of the issue?

Also, I looked at the code example in the README, but it is unclear from there how the `domain` parameter should look like. Could you please clarify this in the README file?

**Comment by ShaneXLi** [comment]
Hi Yanivnik. I also encounter the same error messages from running the two examples (visualize_cnn_random.py and visualize_mlp_random.py). I am just wondering if you have had any luck solving the issue?

**Comment by yanivnik** [comment]
@ShaneXLi I played around with some constants in the code to make it run, but unfortunately the resulting visualizations are still not very similar to the expected results presented in the paper.  @AhmedImtiazPrio could you have a look at these demos?

**Comment by AhmedImtiazPrio** [comment]
Hi @yanivnik @ShaneXLi 

Taking a look, sorry for all the delays with getting back to you. Is this happening everytime you run the current version of example codes?

**Comment by ShaneXLi** [comment]
> Hi @yanivnik @ShaneXLi
> 
> Taking a look, sorry for all the delays with getting back to you. Is this happening everytime you run the current version of example codes?

Hi Ahmed. As the error suggested, the two matrices cannot be multiplied due to their matrix shapes. So this error happens consistently every time I run the current/latest version of example codes. Please take some time to review the codes.

**Comment by AhmedImtiazPrio** [comment]
It looks like an issue raised due to some changes that have been made to the splinecam library. I'll update the examples and ping here.

**Comment by AhmedImtiazPrio** [comment]
@yanivnik  @ShaneXLi  examples updated, please let me know if they are not working as expected!

**Comment by BabaVegato** [comment]
Hello,

With this new version, when launching any of the visualize*.py, I get a CUDA_NOT_INITIALIZED.

The precise error with visualize_mlp_random.py is : 
```
Traceback (most recent call last):
  File "visualize_mlp_random.py", line 58, in <module>
    print('forward and affine equivalency flag ', NN.verify())
  File "/data1/is156025/br270690/anaconda3/envs/splinecam/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/is156025/br270690/improved_projections/splinecam/examples/../splinecam/wrappers.py", line 415, in verify
    fwd_val = self.layers.forward(A)
  File "/data1/is156025/br270690/anaconda3/envs/splinecam/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/data1/is156025/br270690/anaconda3/envs/splinecam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/is156025/br270690/anaconda3/envs/splinecam/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/is156025/br270690/improved_projections/splinecam/examples/../splinecam/wrappers.py", line 59, in forward
    return (self.Abw[...,:-1] @ x.T + self.Abw[...,-1:]).T
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

When the notebook examples are working properly. I used environment.yml, my pytorch is 1.12.1.post201 and cuda is 11.2.
